// Dark Haven - This file is licensed under AGPLv3
// Copyright (c) 2026 Dark Haven Contributors
// See AGPLv3.txt for details.

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DH.FlyingCraft.UI;

/// <summary>
/// Cockpit HUD widget for a flying craft: an always-visible "expand" toggle with a body panel (ammo + reload bar,
/// fuel, mini-radar, speed, coordinates) that the pilot can show/hide. Lives above the hotbar; values are pushed
/// each frame by <see cref="FlyingCraftHudUIController"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FlyingCraftHud : UIWidget
{
    public FlyingCraftHud()
    {
        RobustXamlLoader.Load(this);
        SetExpanded(true); // open by default
    }

    public void SetExpanded(bool expanded)
    {
        BodyPanel.Visible = expanded;
        ExpandButton.Text = Loc.GetString(expanded ? "flyingcraft-hud-collapse" : "flyingcraft-hud-expand");
    }
}
