// Dark Haven - This file is licensed under AGPLv3
// Copyright (c) 2026 Dark Haven Contributors
// See AGPLv3.txt for details.

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._DH.FlyingCraft;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DH.FlyingCraft.UI;

/// <summary>
/// Flying-craft purchase console window: shows the buyer's balance, a buyable catalog (name + price + Buy), and —
/// for craft consoles — a list of nearby spawn points to pick before buying.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FlyingCraftConsoleWindow : FancyWindow
{
    public event Action<string, NetEntity?>? BuyPressed;

    private NetEntity? _selectedSpawner;
    private bool _needsSpawner;

    public FlyingCraftConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(FlyingCraftConsoleState state)
    {
        _needsSpawner = state.NeedsSpawner;
        BalanceLabel.Text = Loc.GetString("flying-craft-console-balance", ("balance", state.Balance));
        SpawnerSection.Visible = state.NeedsSpawner;

        // Drop a stale selection if that spawner is no longer in range.
        if (_selectedSpawner is { } sel && state.Spawners.All(s => s.Spawner != sel))
            _selectedSpawner = null;

        SpawnerList.RemoveAllChildren();
        if (state.NeedsSpawner)
        {
            foreach (var sp in state.Spawners)
            {
                var spawner = sp.Spawner;
                var name = sp.Name;
                var btn = new Button { Text = name };
                btn.OnPressed += _ =>
                {
                    _selectedSpawner = spawner;
                    SelectedSpawnerLabel.Text = Loc.GetString("flying-craft-console-spawn-selected", ("name", name));
                };
                SpawnerList.AddChild(btn);
            }

            SelectedSpawnerLabel.Text = Loc.GetString(_selectedSpawner == null
                ? "flying-craft-console-spawn-none"
                : "flying-craft-console-spawn-selected", ("name", SelectedName(state)));
        }

        CatalogList.RemoveAllChildren();
        foreach (var entry in state.Catalog)
        {
            var proto = entry.Proto;
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            row.AddChild(new Label { Text = entry.Name, HorizontalExpand = true });
            row.AddChild(new Label { Text = Loc.GetString("flying-craft-console-price", ("price", entry.Price)) });

            var buy = new Button
            {
                Text = Loc.GetString("flying-craft-console-buy"),
                Disabled = state.Balance < entry.Price,
                Margin = new Robust.Shared.Maths.Thickness(6, 0, 0, 0),
            };
            buy.OnPressed += _ => BuyPressed?.Invoke(proto, _needsSpawner ? _selectedSpawner : null);
            row.AddChild(buy);

            CatalogList.AddChild(row);
        }
    }

    private string SelectedName(FlyingCraftConsoleState state)
        => state.Spawners.FirstOrDefault(s => s.Spawner == _selectedSpawner)?.Name ?? string.Empty;
}
